deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        -   name: Checkout gh-pages
            uses: actions/checkout@v4
            with:
                ref: gh-pages

        -   name: Download artifact for deployment
            uses: actions/download-artifact@v4
            with:
                name: site-build
                path: docs/.vitepress/dist  # 下载到该目录

        -   name: Set up Git configuration
            run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "github-actions@users.noreply.github.com"

        -   name: Deploy to correct directory
            run: |
                ls -la docs/.vitepress/dist  # 确保构建文件存在
                if [ "${{ github.ref_name }}" == "main" ]; then
                  cp -r docs/.vitepress/dist/* .
                elif [ "${{ github.ref_name }}" == "alpha.x" ]; then
                  mkdir -p alpha
                  cp -r docs/.vitepress/dist/* alpha/
                fi

        -   name: Commit and push changes to gh-pages
            run: |
                git add -A
                git commit -m "Deploy ${{ github.ref_name }} branch" || echo "No changes to commit"
                git push --force origin gh-pages

        -   name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v2